build_from:
  aarch64: xiaoyaliu/alist:latest
  amd64: xiaoyaliu/alist:latest
  armv7: xiaoyaliu/alist:latest
squash: false
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base