name: "小雅Alist"
description: "一个口碑级的alist应用"
version: "1.0"
slug: "xiaoya-alist"
# url: https://gitcode.com/waxgourd/addons
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: "[PROTO:http]://[HOST]:[PORT:5678]"
ports:
  80/tcp: 5678
  2345/tcp: 2345
  2346/tcp: 2346
environment:
  no_proxy: "*.aliyundrive.com"
boot: manual
options:
  alipan_token: ""
  alipan_refresh_token: ""
  alipan_folder_id: ""
  pikpak_conf: ""
  docker_address: ""
  docker_address_ext: ""
  quark_cookie: ""
schema:
  alipan_token: str
  alipan_refresh_token: str
  alipan_folder_id: str
  pikpak_conf: str?
  docker_address: str?
  docker_address_ext: str?
  quark_cookie: str?
